INSERT INTO Deliveries(provider_id, trade_point_id, good_id, count, del_date) VALUES(1, 1, 2, 10, TO_DATE('20.02.2021','dd.mm.yyyy'))
INSERT INTO Deliveries(provider_id, trade_point_id, good_id, count, del_date) VALUES(2, 2, 3, 20, TO_DATE('12.02.2021','dd.mm.yyyy'))
INSERT INTO Deliveries(provider_id, trade_point_id, good_id, count, del_date) VALUES(3, 3, 4, 30, TO_DATE('07.03.2021','dd.mm.yyyy'))
INSERT INTO Deliveries(provider_id, trade_point_id, good_id, count, del_date) VALUES(4, 1, 5, 40, TO_DATE('10.02.2021','dd.mm.yyyy'))
INSERT INTO Deliveries(provider_id, trade_point_id, good_id, count, del_date) VALUES(5, 2, 6, 50, TO_DATE('20.03.2021','dd.mm.yyyy'))
INSERT INTO Deliveries(provider_id, trade_point_id, good_id, count, del_date) VALUES(4, 3, 7, 60, TO_DATE('27.02.2021','dd.mm.yyyy'))
