INSERT INTO Providers(name, user_id) VALUES('Belyi zamok', '4')
INSERT INTO Providers(name, user_id) VALUES('Teremok', '4')
INSERT INTO Providers(name, user_id) VALUES('Snegovichok', '4')
INSERT INTO Providers(name, user_id) VALUES('Lenta', '4')
INSERT INTO Providers(name, user_id) VALUES('Metro', '4')