INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(1, 2, 100, 1, 1, 2)
INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(1, 3, 110, 2, 1, 2)
INSERT INTO Requests(trade_point, good, count, status, user_id) VALUES(1, 4, 90, 0, 2)
INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(2, 5, 80, 3, 1, 2)
INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(2, 6, 70, 4, 0, 2)
INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(2, 7, 60, 1, 0, 2)
INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(2, 8, 50, 2, 0, 2)
INSERT INTO Requests(trade_point, good, count, provider, status, user_id) VALUES(3, 1, 40, 3, 0, 2)
INSERT INTO Requests(trade_point, good, count, status, user_id) VALUES(3, 2, 30, 0, 2)
INSERT INTO Requests(trade_point, good, count, status, user_id) VALUES(3, 3, 20, 0, 2)